// Generated by scripts/build-config.js — не редактировать вручную.
window.FIREBASE_CONFIG = {
  "apiKey": "AIzaSyDuDqAjRB8Uj8Rk62RCCrVpCNeGoSiOkVQ",
  "authDomain": "mots-par-jour.firebaseapp.com",
  "projectId": "mots-par-jour",
  "storageBucket": "mots-par-jour.firebasestorage.app",
  "messagingSenderId": "179725040320",
  "appId": "1:179725040320:web:78b0b9f083b433b8c98b25"
};
